baud_rate: 9600
com_port: COM3
invert_sliders: false
jitter_threshold: 10
reconnect: true
slider_mapping:
  '0':
  - master
  '1':
  - brave.exe
  '2':
  - spotify.exe
  '3':
  - discord.exe
  '4':
  - assetocorsa.exe
